### ISSUE TITLE
I have some problems when running the code

### ISSUE THREAD

**Issue by rrruuunnn** [psaltaath/tadn-mot#4]
Hello, I am sorry to bother you. I have some questions about your program and would like to ask for some advice. In the program precompute_appearance_vectors.py, if the input is the MOT17 dataset, a folder of appearance_vectors_resnet18_train is created. If the input is the UA_DETRAC dataset, a folder similar to appearance_vectors_resnet18_EB_train is created. When running online_training.py with mot17.json, the program will look for a folder similar to appearance_vectors_reid_SDP_train. However, the appearance_vectors_reid_SDP_train folder was not generated in the previous preprocessing process, and the program made an error. So I would like to ask you the above question. Thank you for answering my question in your busy schedule.

**Comment by psaltaath** [comment]
We have updated our code, please check again if the problem is solved (it should be!). Sorry for the late answer
